CPU magic -> uboot
uboot: "U-Boot\
\n🪶With modified boot entries so they look better"

UMSK: "🪶UMS (USB Mass Storage) kernel\
\nMinimal kernel (with embedded initrd) that exposes the whole disk over USB\
\nIt's located in the logo partition, which is hacky but makes it more break-resistant"
uboot -> UMSK

QuillStrap: "🪶QuillStrap\
\nInstalls all other things (mainly via UMS kernel)"
UMSK -> QuillStrap
QuillStrap -> uboot: "Also flashes U-Boot (installs really everything)"

HRDLK: "👥HRDL's kernel"
uboot -> HRDLK

Alpine: "Alpine\
\nMinimal Alpine Linux base system used as initrd"
HRDLK -> Alpine

QuillInit: {|md
🪶🦀Our initialization program. It sets up a few things, like:
- Progress bar for showing boot progress
- Recovery program, which can restore anything below to first boot state, or connect to Wi-Fi for ssh, etc.
- Logs in the user in rootfs (shows login UI, decrypts home directory)
(doesn't wait for systemd to finish booting, so you can type while it's still loading)
- Written in Slint, doesn't rely on a window manager
|}
Alpine -> QuillInit

Gocryptfs: "Gocryptfs\
\n encrypts/decrypts the home directory"
QuillInit -> Gocryptfs: "Decrypts before providing logging data"

FuseOverlay: "🪶fuse-overlayfs setup for rootfs\
\n Allows reverting changes made to Fedora (see below) easier (but makes updates more complicated)\
\n Basically a RW layer for Fedora (except home directories), enabled by default"
QuillInit -> FuseOverlay

Fedora: "Fedora\n Pure ARM fedora with systemd (with a few tweaks for the PineNote)"
FuseOverlay -> Fedora: "Some chroot magic"

Qoms: "🪶🦀Qoms\
\n Quill OS main service"
Fedora -> Qoms
Qoms <-> QuillInit: "Gets login data"

Greetd: "🦀Greetd"
Qoms -> Greetd: "Logs in the user"

Niri: "🦀Niri\
\n Niri's window tiling makes the experience very similar to a tablet's,\
\n but it's Linux+Wayland!"
Greetd -> Niri

Eww: "🦀Eww widgets\
\n For the toolbar\
\n custom look, tweaked for eInk🪶"
EwwDataProvider: "🦀🪶Eww data provider\
\n Talks to eww providing data that it needs"
EwwDataProvider -> Eww: Talking
Dunst: "Dunst\
\n Notifications daemon"
SwayBg: "swaybg\
\n For the wallpaper"
squeekboard: "🦀squeekboard\
\n For the virtual keyboard\
\n(maliit keyboard did not work)"
PinenoteService: "🦀👥Phantomas pinenote service\
\n Provides interface to change screen settings"
EwwDataProvider <-> PinenoteService: "dbus"

Niri -> Eww
Niri -> EwwDataProvider
Niri -> Dunst
Niri -> SwayBg
Niri -> squeekboard
Niri -> PinenoteService

NwgDrawer: "nwg-drawer as app launcher"
Niri -> NwgDrawer

OtherApps: "And all other apps you want"
NwgDrawer -> OtherApps

Xournalpp: "Xournalpp\
\n with a custom config and toolbar🪶"
NwgDrawer -> Xournalpp
